### ISSUE TITLE
Search for Parts of words

### ISSUE THREAD

**Issue by guebert** [searchdaimon/enterprise-search#13]
A key feature for use in an office which is document oriented is the ability of searching for parts of words like "enterpri*".

**Comment by guebert** [comment]
Anything new ... Beta V3?

Michael

**Comment by guebert** [comment]
Anything new ... :-(

Michael

**Comment by runarbu** [comment]
"Fuzzy search" as this is known as will not be implemented any time soon. We have unfortunately found its benefits too small for taking on the costly and complex task to implement it. Our time is better spent elsewhere.

We do however support stemming. For example a search for “car” may return document containing car, cars, carring etc. Thus words all have car as its root form. But words like carbonara, carbon, carburetor etc. are not derived from the word car and will therefore not be search for. Neither will a search for "search*" return "searchdaimon".
