### ISSUE TITLE
No answer from SD-team (support / commerce) since MONTH - is this project dead?

### ISSUE THREAD

**Issue by guebert** [searchdaimon/enterprise-search#32]
Hallo,

I'm looking for an replacement of our (old but good working) IBM Omnifind Yahoo Edition. I need search for parts of words like "search*" which finds also "searchdaimon".

See my postings here:

http://www.searchdaimon.com/forum/viewthread/1476/

https://github.com/searchdaimon/enterprise-search/issues/13

I asked, if this will be implemented in SD, maybe as paid extra feature.

No reaction on mails 2015-03-26, 04-07, 04-16 and 05-05 ... :-(

Anybody here who is interested in this feature? (I think without this, a search engine is nearly useless ...)

Michael

**Comment by runarbu** [comment]
It looks like your question has been overlooked. I am sorry about that. I will look into what happened here.

"Fuzzy search" as this is known as will not be implemented any time soon. We have unfortunately found its benefits too small for taking on the costly and complex task to implement it. Our time is better spent elsewhere.

We do however support stemming. For example a search for “car” may return document containing car, cars, carring etc. Thus words all have car as its root form. But words like carbonara, carbon, carburetor etc. are not derived from the word car and will therefore not be search for. Neither will a search for "search*" return "searchdaimon".
